spring.application.name=realestateerp
spring.datasource.url=jdbc:postgresql://localhost:5432/realestateerp
spring.datasource.username=erp_app
spring.datasource.password=erpapp2026
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${H8dyRoi7QUTwPVuthJX/pHjGGMVG1n8ef41bNDdTDqg=}
jwt.expiration=${JWT_EXPIRATION:86400000}